export { coursesKeys, seriesKeys } from './keys';
export { useCourses } from './queries/useCourses';
export { useCourse } from './queries/useCourse';
export { useSeries } from './queries/useSeries';
export { useCreateCourse } from './mutations/useCreateCourse';
export { useAddLesson } from './mutations/useAddLesson';
export type { AddLessonVars } from './mutations/useAddLesson';
export { useAddSlide } from './mutations/useAddSlide';
export type { AddSlideVars } from './mutations/useAddSlide';
export { useUpdateSlide } from './mutations/useUpdateSlide';
export type { UpdateSlideVars } from './mutations/useUpdateSlide';
export { apiFetch, ApiError } from './client';
