export { coursesKeys } from './keys';
export { useCourses } from './queries/useCourses';
export { useCourse } from './queries/useCourse';
export { useCreateCourse } from './mutations/useCreateCourse';
export { useAddSection } from './mutations/useAddSection';
export type { AddSectionVars } from './mutations/useAddSection';
export { useAddSlide } from './mutations/useAddSlide';
export type { AddSlideVars } from './mutations/useAddSlide';
export { useUpdateSlide } from './mutations/useUpdateSlide';
export type { UpdateSlideVars } from './mutations/useUpdateSlide';
export { apiFetch, ApiError } from './client';
